apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-167844411
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-167844411
    app.kubernetes.io/part-of: test-app-167844411
  name: java-quarkus-167844411
  namespace: xnzpir0p-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: java-quarkus-167844411
    weight: null
status: {}
